export const noticies = [
            {
                "id": "63f8a8a3012ecaaf049b8335",
                "category": "sell",
                "image": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "Rassel",
            },
            {
                "id": "63f8a8a3012ecaaf049b8335",
                "category": "sell",
                "image": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "Rassel",
            },
            {
                "id": "63f8a8a3012ecaaf049b8335",
                "category": "sell",
                "image": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "Rassel",
            },
            {
                "id": "63f8a8a3012ecaaf049b8335",
                "category": "sell",
                "image": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "Rassel",
            },
            {
                "id": "63f8a8a3012ecaaf049b8335",
                "category": "sell",
                "image": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "Rassel",
            },
            {
                "id": "63f8a8a3012ecaaf049b8335",
                "category": "sell",
                "image": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "Rassel",
            },
            {
                "id": "63f8a8a3012ecaaf049b8335",
                "category": "sell",
                "image": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "Rassel",
            },
            {
                "id": "63f8a8a3012ecaaf049b8335",
                "category": "sell",
                "image": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "Rassel",
            },
            {
                "id": "63f8a8a3012ecaaf049b8335",
                "category": "sell",
                "image": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "Rassel",
            },
            {
                "id": "63f8a8a3012ecaaf049b8335",
                "category": "sell",
                "image": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "Rassel",
            },
            {
                "id": "63f8a8a3012ecaaf049b8335",
                "category": "sell",
                "image": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "Rassel",
            },
            {
                "id": "63f8a8a3012ecaaf049b8335",
                "category": "sell",
                "image": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "Rassel",
            },
            {
                "id": "63f8a8a3012ecaaf049b8335",
                "category": "sell",
                "image": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "Rassel",
            },
            {
                "id": "63f8a8a3012ecaaf049b8335",
                "category": "sell",
                "image": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "Rassel",
            },
            {
                "id": "63f8a8a3012ecaaf049b8335",
                "category": "sell",
                "image": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "Rassel",
            },
            {
                "id": "63f8a8a3012ecaaf049b8335",
                "category": "sell",
                "image": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "Rassel",
            },
            {
                "id": "63f8a8a3012ecaaf049b8335",
                "category": "sell",
                "image": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "Rassel",
            },
            {
                "id": "63f8a8a3012ecaaf049b8335",
                "category": "sell",
                "image": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "Rassel",
            },
            {
                "id": "63f8a8a3012ecaaf049b8335",
                "category": "sell",
                "image": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "Rassel",
            },
            {
                "id": "63f8a8a3012ecaaf049b8335",
                "category": "sell",
                "image": "https://res.cloudinary.com/pet-support/image/upload/v1677240482/avatars/sgz7p8mnj7kzmrupqkmv.jpg",
                "location": "Lviv",
                "date": "07.09.22",
                "sex": "Rassel",
            },
            
];